apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clova-issuer
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dev.umijs@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: clova-issuer-secret
    solvers:
    - http01:
        ingress:
          class: istio
